"use client";
import { useLanguage, LanguageSwitcher } from "@/components/language";
import { useState } from "react";
import { ArrowRight, ArrowUpRight, Check, MapPin, Globe2, FileCheck2, ClipboardList, Car, ReceiptText, ShieldCheck, Handshake, Phone, Mail, Menu, X, MessageCircle, CheckCircle2, Route, ChevronDown } from "lucide-react";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import { Sheet, SheetContent, SheetTrigger, SheetTitle, SheetDescription, SheetClose } from "@/components/ui/sheet";
import { QuoteForm } from "@/components/quote-form";
import { emptySettings, type Settings } from "@/lib/quotes";
export function Brand({inverse=false}:{inverse?:boolean}){const {t,language}=useLanguage();return <a href="/" className={`brand-lockup ${inverse?"brand-inverse":""}`} aria-label={t("CARREG SPAIN home")}><img src="/images/carreg-logo.jpeg" alt="" width={58} height={58}/><span><strong>CARREG <em>SPAIN</em></strong><small>{t("DRIVE YOUR PLANS FURTHER")}</small></span></a>;}
const nav=[{href:"#services",label:"Our services"},{href:"#how-it-works",label:"How it works"},{href:"#why-carreg",label:"Why CARREG"},{href:"#faq",label:"FAQs"}];
export function SiteHeader(){const {t,language}=useLanguage();return <><div className="utility-bar"><div className="container"><span><MapPin size={13}/> {t("Vehicle registration, across Spain")}</span><span>{t("For expats, residents & imports")} <span className="spanish-mark" aria-hidden="true"/></span></div></div><header className="site-header"><div className="container header-inner"><Brand/><nav aria-label={t("Main navigation")}>{nav.map(n=><a href={`/${n.href}`} key={n.href}>{t(n.label)}</a>)}</nav><LanguageSwitcher/><a href="/#quote" className="button button-red header-quote">{t("Request your quote")} <ArrowUpRight size={17}/></a><Sheet><SheetTrigger asChild><button className="mobile-nav-toggle" aria-label={t("Open navigation")}><Menu size={25}/></button></SheetTrigger><SheetContent className="mobile-nav" showCloseButton={false}><SheetClose className="dialog-close-local" aria-label={t("Close")}><X size={20}/></SheetClose><SheetTitle>CARREG SPAIN</SheetTitle><SheetDescription>{t("Vehicle registration made simple.")}</SheetDescription><nav>{nav.map(n=><SheetClose asChild key={n.href}><a href={`/${n.href}`}>{t(n.label)}</a></SheetClose>)}<SheetClose asChild><a href="/#quote" className="button button-red">{t("Request your quote")} <ArrowRight size={17}/></a></SheetClose></nav></SheetContent></Sheet></div></header></>;}
export function SiteFooter({settings=emptySettings}:{settings?:Settings}){const {t,language}=useLanguage();return <footer className="site-footer"><div className="container footer-main"><div><Brand inverse/><p>{t("We handle the paperwork.")}<br/>{t("You enjoy the drive.")}</p></div><div><h3>{t("Here to help")}</h3><a href="/#services">{t("Registration services")}</a><a href="/#how-it-works">{t("How it works")}</a><a href="/#faq">{t("Common questions")}</a></div><div><h3>{t("Let’s talk about your car")}</h3>{settings.contactEmail&&<a href={`mailto:${settings.contactEmail}`}><Mail size={16}/>{settings.contactEmail}</a>}{settings.phone&&<a href={`tel:${settings.phone.replace(/[^+\d]/g,"")}`}><Phone size={16}/>{settings.phone}</a>}<a href="/#quote">{t("Request a personalised quote")} <ArrowUpRight size={15}/></a><span className="footer-coverage"><MapPin size={15}/> {t("Spain-wide service")}</span></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} {settings.legalName||"CARREG SPAIN"}</span><div><a href="/privacy">{t("Privacy & your request")}</a><a href="/admin">{t("Owner area")}</a></div><span className="spanish-mark" aria-hidden="true"/></div></footer>;}
const services=[{icon:Globe2,title:"Import advice",text:"Bringing your own car or buying abroad? Understand the registration route before you get started.",tag:"START WITH CLARITY"},{icon:FileCheck2,title:"DGT paperwork",text:"Support with the documents and application needed to register your vehicle in Spain.",tag:"PAPERWORK, HANDLED"},{icon:Car,title:"ITV support",text:"Guidance on technical documents and the inspection stage, with your particular vehicle in mind.",tag:"GET INSPECTION-READY"},{icon:ReceiptText,title:"Taxes & fees",text:"Understand the applicable charges and what your personalised quote includes before proceeding.",tag:"KNOW THE COSTS"},{icon:ShieldCheck,title:"Spanish plates",text:"Help through the final registration steps, so you can move towards driving on Spanish plates.",tag:"THE FINAL STRETCH"}];
const faqs=[
 ["What information do you need for a quote?","Start with your vehicle’s make, model, first registration year, fuel type, country of registration and your plans in Spain. If you have the VIN, engine size and CO₂ figure, those can help us assess your case. You don’t need to upload documents to send the first enquiry."],
 ["Can you help with a UK-registered vehicle?","Yes—tell us it is registered in the United Kingdom when requesting your quote. UK and other non-EU imports can involve customs documentation as well as the Spanish registration process. We’ll review your vehicle and circumstances before advising on next steps."],
 ["Which documents might I need?","Depending on your case, these can include the original registration document, proof of ownership, identification, technical conformity documentation and Spanish ITV paperwork. Customs documents may also be relevant for non-EU imports. We’ll explain what is needed for your particular vehicle."],
 ["How much does registering my car cost?","There is no single price that fits every vehicle. Its origin, age, technical details, your circumstances and the location in Spain can affect the work and charges involved. Request a quote so we can review those details and explain the costs."],
 ["How long does the process take?","Timing depends on the documents available, any technical work needed and appointment availability. After reviewing your enquiry, we can discuss a realistic sequence and timeframe for your case. Tell us if you have a planned move or arrival date."],
 ["My vehicle is already in Spain. Can I still enquire?","Absolutely. Select ‘Already in Spain with foreign plates’ in the quote form and tell us where it is located. We’ll assess the next steps. Registration requirements and your current right to drive should be checked for your own circumstances."],
 ["What if I don’t have all the technical information?","You can still get in touch. Leave optional fields blank and choose ‘Not sure’ where offered. We’ll let you know which additional details or documents would help us assess your vehicle."]
];
export function CarregWebsite({settings}: {settings:Settings|null}){const {t,language}=useLanguage();const info=settings||emptySettings;const [checklist,setChecklist]=useState(false);return <><a href="#main" className="skip-link">{t("Skip to content")}</a><SiteHeader/><main id="main">
 <section className="hero"><div className="hero-photo"><img src="/images/coastal-drive.png" alt={t("A dark blue car overlooking the Mediterranean coast in Spain")} fetchPriority="high"/><div className="hero-photo-shade"/></div><div className="container hero-layout"><div className="hero-copy"><div className="eyebrow"><span/> {t("A NEW CHAPTER. THE SAME CAR.")}</div><h1>{t("New roads.")}<br/>{t("Less paperwork.")}<br/><em>{t("Hello, Spain.")}</em></h1><p>{t("Make your move with confidence. We help you navigate vehicle registration in Spain, from the first question to your Spanish plates.")}</p><div className="hero-buttons"><a href="#quote" className="button button-red">{t("Request your quote")} <ArrowRight size={18}/></a><a href="#how-it-works" className="hero-secondary">{t("See how it works")} <ArrowDownCircle/></a></div><div className="hero-assurances"><span><CheckCircle2 size={17}/> {t("Personal support")}</span><span><CheckCircle2 size={17}/> {t("No-obligation enquiry")}</span></div></div><div className="hero-note"><span><Route size={21}/></span><div><strong>{t("Your car. Your next adventure.")}</strong><p>{t("We’ll help with the part in between.")}</p></div></div></div><div className="hero-scroll"><span>{t("SIMPLER ROADS IN SPAIN")}</span><span className="spanish-mark"/></div></section>
 <section className="service-ribbon" aria-label={t("Registration support")}><div className="container">{services.map(({icon:Icon,title})=><a key={t(title)} href="#services"><Icon size={23}/><span>{t(title)}</span></a>)}</div></section>
 <section id="services" className="section services-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">{t("FROM FOREIGN PLATES TO FAMILIAR ROADS")}</p><h2>{t("A clearer route to")}<br/>{t("Spanish registration.")}</h2></div><p>{t("Moving countries comes with enough to think about.")}<br className="desktop-break"/> {t("Let’s make the vehicle paperwork one less thing.")}</p></div><div className="service-grid">{services.map(({icon:Icon,title,text,tag},i)=><article className="service-card" key={t(title)}><div className="service-card-top"><span><Icon size={28} strokeWidth={1.55}/></span><small>0{i+1}</small></div><h3>{t(title)}</h3><p>{t(text)}</p><span className="service-tag">{t(tag)}</span></article>)}<article className="service-card service-card-cta"><Handshake size={36} strokeWidth={1.5}/><h3>{t("Not sure where to start?")}</h3><p>{t("Tell us about your car.")}<br/>{t("We’ll take it from there.")}</p><a href="#quote">{t("Let’s talk")} <ArrowUpRight size={21}/></a></article></div></div></section>
 <section id="how-it-works" className="section process-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">{t("A LITTLE INFORMATION. A CLEARER PLAN.")}</p><h2>{t("Your journey, simplified.")}</h2></div><a href="#quote" className="text-link">{t("Start with your vehicle")} <ArrowUpRight size={18}/></a></div><div className="process-grid">{[{n:"01",title:"Tell us about your vehicle",text:"Share the basics and your plans for Spain using our guided quote form."},{n:"02",title:"Get a personalised plan",text:"We review your enquiry and explain the next steps, documents and costs."},{n:"03",title:"Let’s handle the details",text:"Once you choose to proceed, we guide you through the agreed registration work."},{n:"04",title:"Enjoy your Spanish chapter",text:"Complete the required steps and get ready for life on Spanish plates."}].map(s=><article key={s.n}><div className="process-number">{s.n}</div><h3>{t(s.title)}</h3><p>{t(s.text)}</p></article>)}</div></div></section>
 <section id="why-carreg" className="section why-section"><div className="container why-layout"><div className="why-visual"><img src="/images/coastal-drive.png" alt={t("A coastal road winding past a white Spanish village")} loading="lazy"/><div className="why-caption"><span>{t("MORE ROADS. BRIGHTER DAYS.")}</span><strong>{t("Bring your car.")}<br/>{t("Make yourself at home.")}</strong></div><img className="why-brand-seal" src="/images/carreg-logo.jpeg" alt={t("CARREG SPAIN — Drive your plans further")} loading="lazy"/></div><div className="why-copy"><p className="eyebrow">{t("PROFESSIONAL. PERSONAL. STRAIGHTFORWARD.")}</p><h2>{t("A familiar face")}<br/>{t("for unfamiliar paperwork.")}</h2><p>{t("Whether you’re relocating, importing a car or sorting out foreign plates, your circumstances matter. We start by understanding them.")}</p><div className="why-points"><div><span><UserIcon/></span><div><h3>{t("Your vehicle, your situation")}</h3><p>{t("Guidance based on the car you actually own and the journey you’re making.")}</p></div></div><div><span><ReceiptText size={22}/></span><div><h3>{t("Clarity before commitment")}</h3><p>{t("Understand the proposed work and charges before deciding to go ahead.")}</p></div></div><div><span><MapPin size={22}/></span><div><h3>{t("Support across Spain")}</h3><p>{t("From coastal towns to city life, tell us where you’re heading and we’ll assess your needs.")}</p></div></div></div><a href="#quote" className="text-link">{t("Let’s get your journey started")} <ArrowUpRight size={18}/></a></div></div></section>
 <section id="quote" className="section quote-section"><div className="container quote-layout"><aside className="quote-intro"><p className="eyebrow">{t("YOUR CAR. YOUR PERSONALISED QUOTE.")}</p><h2>{t("Let’s get you")}<br/>{t("on the right road.")}</h2><p>{t("Tell us a little about your vehicle and what you need. We’ll review your request and get in touch with the next steps.")}</p><ul><li><Check size={18}/> {t("No-obligation enquiry")}</li><li><Check size={18}/> {t("No documents needed to start")}</li><li><Check size={18}/> {t("A quote based on your vehicle")}</li></ul><div className="quote-help"><ClipboardList size={25}/><h3>{t("Useful to have nearby")}</h3><p>{t("Your current registration document usually contains the vehicle details we ask for.")}</p><button type="button" onClick={()=>setChecklist(!checklist)} aria-expanded={checklist}>{t(checklist?"Hide checklist":"See the quick checklist")}<ChevronDown size={15} className={checklist?"rotated":""}/></button>{checklist&&<ul className="quick-checklist"><li>{t("Make, model and first registration year")}</li><li>{t("Country and current registration plate")}</li><li>{t("Engine size and CO₂ figure, if known")}</li><li>{t("Your intended location in Spain")}</li></ul>}</div>{info.whatsapp&&<a className="quote-contact" href={`https://wa.me/${info.whatsapp.replace(/\D/g,"")}`} target="_blank" rel="noreferrer"><MessageCircle size={19}/> {t("Prefer to chat? WhatsApp us")} <ArrowUpRight size={16}/></a>}</aside><QuoteForm/></div></section>
 <section id="faq" className="section faq-section"><div className="container faq-layout"><div><p className="eyebrow">{t("A FEW THINGS YOU MIGHT BE WONDERING")}</p><h2>{t("Good questions.")}<br/>{t("Clear answers.")}</h2><p>{t("Every vehicle has its own story.")}<br/>{t("If yours isn’t covered here, just ask.")}</p><a href="#quote" className="text-link">{t("Ask about your vehicle")} <ArrowUpRight size={17}/></a></div><Accordion type="single" collapsible className="faq-list">{faqs.map(([q,a],i)=><AccordionItem key={t(q)} value={`faq-${i}`}><AccordionTrigger>{t(q)}</AccordionTrigger><AccordionContent>{t(a)}{i===2&&<p className="official-guidance">{t("Official guidance:")} <a href="https://www.dgt.es/nuestros-servicios/tu-vehiculo/quieres-traer-o-llevarte-un-vehiculo-del-extranjero/matricular-un-vehiculo-proveniente-de-la-ue/" target="_blank" rel="noreferrer">{t("EU vehicles")}</a> · <a href="https://www.dgt.es/nuestros-servicios/tu-vehiculo/quieres-traer-o-llevarte-un-vehiculo-del-extranjero/importar-un-vehiculo-de-fuera-de-la-ue/" target="_blank" rel="noreferrer">{t("Non-EU vehicles")}</a></p>}</AccordionContent></AccordionItem>)}</Accordion></div></section>
 <section className="final-cta"><div className="container"><div><p className="eyebrow">{t("LESS ADMIN. MORE ADVENTURE.")}</p><h2>{t("Spain is calling.")}<br/>{t("Let’s bring your car along.")}</h2></div><a href="#quote" className="button button-white">{t("Request your quote")} <ArrowUpRight size={20}/></a></div></section>
 </main><SiteFooter settings={info}/><a href="#quote" className="mobile-quote button button-red">{t("Request your quote")} <ArrowRight size={18}/></a></>;}
function ArrowDownCircle(){return <span className="round-arrow"><ChevronDown size={15}/></span>;}
function UserIcon(){return <Handshake size={22}/>;}
