"use client";
import { useLanguage, LanguageSwitcher } from "@/components/language";
import { useState, useEffect, useCallback, useRef } from "react";
import { Search, RefreshCw, Download, ArrowUpRight, ArrowRight, ArrowLeft, Inbox, FileCheck2, Clock3, CheckCircle2, Mail, Phone, MessageCircle, Loader2, Save, Settings2, LockKeyhole } from "lucide-react";
import { Brand } from "@/components/carreg-website";
import { QuoteSummary } from "@/components/quote-form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Dialog, DialogClose, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { STATUSES, settingsSchema, vehicleLabel, countryLabel, type QuoteRecord, type Status, type Settings } from "@/lib/quotes";
import { LANGUAGE_REGIONS, localizedError, translator, type Language } from "@/lib/i18n";
type InboxView={quotes:QuoteRecord[];total:number;page:number;counts:Record<string,number>;settings:Settings};
const date=(n:number,language:Language)=>new Date(n).toLocaleString(LANGUAGE_REGIONS[language],{day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"});
async function post<T>(action:string,data:unknown){const r=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,data})});const j=await r.json() as T & {error?:string};if(!r.ok)throw new Error(j.error||"Your changes could not be saved.");return j;}
export function EnquiryInbox(){const {t,language}=useLanguage();
 const [view,setView]=useState<InboxView|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[page,setPage]=useState(0),[selected,setSelected]=useState<QuoteRecord|null>(null);const requests=useRef(0);
 const load=useCallback(async()=>{const n=++requests.current;setLoading(true);try{const r=await fetch(`/api/admin?${new URLSearchParams({q:query,status,page:String(page)})}`,{cache:"no-store"});const j=await r.json() as InboxView & {error?:string};if(!r.ok)throw new Error(j.error);if(n===requests.current){setView(j);setError("");}}catch(e){if(n===requests.current)setError(e instanceof Error?e.message:"The inbox could not be loaded.");}finally{if(n===requests.current)setLoading(false);}},[query,status,page]);
 useEffect(()=>{void load();return()=>{requests.current++;};},[load]);
 async function exportCsv(){try{const r=await fetch(`/api/admin?${new URLSearchParams({q:query,status,export:"csv",lang:language})}`,{cache:"no-store"});if(!r.ok){const j=await r.json() as {error?:string};throw new Error(j.error)}const blob=await r.blob();const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="carreg-enquiries.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:"Export failed.");}}
 return <div className="admin-site"><header className="admin-header container"><Brand/><LanguageSwitcher/><a className="button button-outline" href="/">{t("View website")} <ArrowUpRight size={17}/></a></header><main className="container admin-main"><div className="admin-title"><div><p className="eyebrow"><LockKeyhole size={13}/> {t("OWNER AREA")}</p><h1>{t("Your enquiry inbox.")}</h1><p>{t("From a first question to a car on Spanish plates.")}</p></div><button className="button button-outline" disabled={loading} onClick={()=>void load()}><RefreshCw size={17} className={loading?"spin":""}/> {t("Refresh")}</button></div>
 {error&&<div className="form-alert" role="alert">{localizedError(language,error)}</div>}
 <Tabs defaultValue="enquiries" className="inbox-tabs"><TabsList><TabsTrigger value="enquiries"><Inbox size={16}/> {t("Enquiries")}</TabsTrigger><TabsTrigger value="settings"><Settings2 size={16}/> {t("Business details")}</TabsTrigger></TabsList><TabsContent value="enquiries"><div className="inbox-stats">{[{id:"new",label:"New enquiries",icon:Inbox},{id:"reviewing",label:"In review",icon:Clock3},{id:"quoted",label:"Quoted",icon:FileCheck2},{id:"closed",label:"Closed",icon:CheckCircle2}].map(({id,label,icon:Icon})=><button key={id} className={status===id?"selected":""} onClick={()=>{setStatus(status===id?"all":id);setPage(0);}}><div><span>{t(label)}</span><strong>{view?.counts[id]||0}</strong></div><Icon size={25}/></button>)}</div>
 <div className="inbox-toolbar"><form onSubmit={e=>{e.preventDefault();setQuery(search);setPage(0)}}><Search size={18}/><Input aria-label={t("Search enquiries")} placeholder={t("Name, email, vehicle or reference")} value={search} onChange={e=>setSearch(e.target.value)}/><button type="submit" className="button button-navy">{t("Search")}</button></form><Select value={status} onValueChange={v=>{setStatus(v);setPage(0)}}><SelectTrigger aria-label={t("Filter by status")}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">{t("All statuses")}</SelectItem>{STATUSES.map(s=><SelectItem key={s} value={s}>{t(s)}</SelectItem>)}</SelectContent></Select><button className="button button-outline" disabled={!view?.total||loading} onClick={()=>void exportCsv()}><Download size={17}/> {t("Export CSV")}</button></div>
 <div className="inbox-table">{loading&&!view?<div className="inbox-empty"><Loader2 className="spin" size={30}/><h2>{t("Opening your inbox…")}</h2></div>:!view?.quotes.length?<div className="inbox-empty"><Inbox size={43}/><h2>{t(query||status!=="all"?"No matching enquiries.":"Your next customer starts here.")}</h2><p>{t(query||status!=="all"?"Try another search or show all statuses.":"Quote requests submitted through your website will appear here.")}</p><a href="/#quote" className="button button-outline">{t("Open the quote form")} <ArrowUpRight size={16}/></a></div>:<Table><TableHeader><TableRow><TableHead>{t("Customer")}</TableHead><TableHead>{t("Vehicle")}</TableHead><TableHead>{t("Status")}</TableHead><TableHead>{t("Received")}</TableHead><TableHead><span className="sr-only">{t("Open enquiry")}</span></TableHead></TableRow></TableHeader><TableBody>{view.quotes.map(q=><TableRow key={q.id}><TableCell><strong>{q.data.name}</strong><span>{q.data.email}</span></TableCell><TableCell><strong>{vehicleLabel(q.data)}</strong><span>{q.data.country==="Other"?q.data.otherCountry:t(q.data.country)} → {t(q.data.province)}</span></TableCell><TableCell><span className={`status-badge status-${t(q.status)}`}>{t(q.status)}</span></TableCell><TableCell><strong>{date(q.createdAt,language)}</strong><span>{q.reference}</span></TableCell><TableCell><button className="open-enquiry" onClick={()=>setSelected(q)} aria-label={t("Open enquiry from {name}",{name:q.data.name})}>{t("Open")} <ArrowUpRight size={15}/></button></TableCell></TableRow>)}</TableBody></Table>}</div>
 <div className="inbox-pagination"><span>{t("Enquiries: {count}",{count:view?.total||0})}{view?.total?` · ${t("Page {page} of {pages}",{page:page+1,pages:Math.ceil(view.total/25)})}`:""}</span><div><button aria-label={t("Previous page")} disabled={page===0||loading} onClick={()=>setPage(v=>v-1)}><ArrowLeft size={18}/></button><button aria-label={t("Next page")} disabled={!view||((page+1)*25>=view.total)||loading} onClick={()=>setPage(v=>v+1)}><ArrowRight size={18}/></button></div></div><p className="inbox-note">{t("Requests are saved here. Email and WhatsApp replies open in your own apps; automatic email notifications are not enabled.")}</p>
 </TabsContent><TabsContent value="settings">{view&&<BusinessSettings settings={view.settings} onSaved={s=>setView({...view,settings:s})}/>}</TabsContent></Tabs>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="enquiry-dialog" showCloseButton={false}><DialogClose className="dialog-close-local">{t("Close")}</DialogClose>{selected&&<EnquiryDetails key={`${selected.id}-${selected.version}`} quote={selected} onSaved={q=>{setSelected(q);void load();}}/>}</DialogContent></Dialog>
 </main></div>;
}
function EnquiryDetails({quote:q,onSaved}:{quote:QuoteRecord;onSaved:(q:QuoteRecord)=>void}){const {t,language}=useLanguage();const [status,setStatus]=useState<Status>(q.status),[notes,setNotes]=useState(q.notes),[error,setError]=useState(""),[busy,setBusy]=useState(false);return <><p className="eyebrow">{q.reference}</p><DialogTitle>{q.data.name}</DialogTitle><DialogDescription>{vehicleLabel(q.data)} · {t("Received")} {date(q.createdAt,language)}</DialogDescription><div className="enquiry-contact"><a href={`mailto:${q.data.email}?subject=${encodeURIComponent(translator(q.data.language||"en")("Your CARREG SPAIN enquiry {reference}",{reference:q.reference}))}`}><Mail size={16}/> {t("Email")}</a>{q.data.phone&&<a href={`tel:${q.data.phone.replace(/[^+\d]/g,"")}`}><Phone size={16}/> {t("Call")}</a>}{q.data.phone&&q.data.contact==="WhatsApp"&&<a href={`https://wa.me/${q.data.phone.replace(/\D/g,"")}`} target="_blank" rel="noreferrer"><MessageCircle size={16}/> WhatsApp</a>}</div><QuoteSummary data={q.data}/><form className="enquiry-management" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{const result=await post<{quote:QuoteRecord}>("update",{id:q.id,version:q.version,status,notes});onSaved(result.quote);}catch(e){setError(e instanceof Error?e.message:"Save failed.");}finally{setBusy(false);}}}><div className="form-field"><label id="enquiry-status-label">{t("Enquiry status")}</label><Select value={status} onValueChange={v=>setStatus(v as Status)}><SelectTrigger aria-labelledby="enquiry-status-label"><SelectValue/></SelectTrigger><SelectContent>{STATUSES.map(s=><SelectItem value={s} key={s}>{t(s)}</SelectItem>)}</SelectContent></Select></div><div className="form-field"><label htmlFor="internal-notes">{t("Internal notes")}</label><Textarea id="internal-notes" value={notes} onChange={e=>setNotes(e.target.value)} rows={4} maxLength={4000} placeholder={t("Next steps, quotation details or follow-up notes…")}/><p className="field-hint">{t("Only visible in your owner inbox.")}</p></div>{error&&<div className="form-alert" role="alert">{localizedError(language,error)}</div>}<button type="submit" className="button button-red" disabled={busy}>{busy?<Loader2 size={17} className="spin"/>:<Save size={17}/>} {t("Save changes")}</button></form></>;}
function BusinessSettings({settings,onSaved}:{settings:Settings;onSaved:(s:Settings)=>void}){const {t,language}=useLanguage();const [values,setValues]=useState(settings),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");return <form className="business-settings" onSubmit={async e=>{e.preventDefault();setError("");setMessage("");const parsed=settingsSchema.safeParse(values);if(!parsed.success){setError(parsed.error.issues[0].message);return;}setBusy(true);try{const result=await post<{settings:Settings}>("settings",parsed.data);setMessage("Business details saved. They are now displayed on your website.");onSaved(result.settings);}catch(e){setError(e instanceof Error?e.message:"Save failed.");}finally{setBusy(false);}}}><p className="eyebrow">{t("MAKE IT YOURS")}</p><h2>{t("Your business details.")}</h2><p>{t("Add the contact information you want customers to see. These details appear on the website and its privacy information.")}</p><div className="form-grid">{[{key:"contactEmail",label:"Customer contact email",placeholder:"Your business email",type:"email"},{key:"phone",label:"Business phone",placeholder:"Include the country code",type:"tel"},{key:"whatsapp",label:"WhatsApp number",placeholder:"International format, e.g. +34…",type:"tel"},{key:"legalName",label:"Legal business name",placeholder:"Name of the business operating CARREG SPAIN",type:"text"},{key:"address",label:"Business address",placeholder:"Your published business address",type:"text"}].map(f=><div className={`form-field ${f.key==="address"?"full-field":""}`} key={f.key}><label htmlFor={`setting-${f.key}`}>{t(f.label)}</label><Input id={`setting-${f.key}`} type={f.type} placeholder={t(f.placeholder)} value={values[f.key as keyof Settings]} onChange={e=>setValues({...values,[f.key]:e.target.value})}/></div>)}</div><p className="field-hint">{t("Contact details are optional while you review the site. Your owner sign-in is managed separately.")}</p>{error&&<div className="form-alert" role="alert">{localizedError(language,error)}</div>}{message&&<p className="save-success" role="status">{t(message)}</p>}<button type="submit" disabled={busy} className="button button-red">{busy?<Loader2 className="spin" size={17}/>:<Save size={17}/>} {t("Save business details")}</button></form>;}
