"use client";
import { useLanguage, LanguageSwitcher } from "@/components/language";
import { useState, useRef, useEffect } from "react";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowRight, ArrowLeft, Check, CheckCircle2, Car, MapPin, UserRound, ClipboardCheck, LockKeyhole, Loader2, Pencil, ChevronDown } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { localizedError } from "@/lib/i18n";
import { Progress } from "@/components/ui/progress";
import { COUNTRIES, PROVINCES, TYPES, FUELS, PURPOSES, STEP_FIELDS, emptyQuote, quoteSchema, vehicleLabel, countryLabel, type QuoteInput, type QuoteData } from "@/lib/quotes";

const steps=[{title:"Your vehicle",icon:Car},{title:"Your plans",icon:MapPin},{title:"Contact details",icon:UserRound},{title:"Review & send",icon:ClipboardCheck}];
export function QuoteSummary({data,onEdit}:{data:QuoteInput;onEdit?:(step:number)=>void}){const {t,language}=useLanguage();
 const groups=[{title:"Your vehicle",step:0,rows:[["Vehicle",vehicleLabel(data)],["Type / fuel",`${t(data.vehicleType)} · ${t(data.fuel)}`],["Registered in",data.country === "Other" ? data.otherCountry : t(data.country)],["Current plate",data.registration],["VIN / chassis",data.vin],["Engine",data.engineCC?`${data.engineCC} cc`:""],["CO₂",data.co2?`${data.co2} g/km`:""],["Mileage",data.mileage?`${data.mileage} km`:""]]},{title:"Your plans",step:1,rows:[["Reason",t(data.purpose)],["Vehicle in Spain",t(data.inSpain)],["Location",[data.town,t(data.province)].filter(Boolean).join(", ")],["Steering",t(data.steering)],["Certificate of conformity",t(data.coc)],["Modifications",t(data.modified)],["Timeframe",t(data.timeframe)]]},{title:"Contact details",step:2,rows:[["Name",data.name],["Email",data.email],["Phone",data.phone],["Preferred contact",t(data.contact)],["Customer language",t(data.language||"en")],["Your notes",data.notes]]}];
 return <div className="quote-summary">{groups.map(g=><section key={t(g.title)}><div className="summary-heading"><h4>{t(g.title)}</h4>{onEdit&&<button type="button" onClick={()=>onEdit(g.step)}><Pencil size={14}/> {t("Edit")}</button>}</div><dl>{g.rows.filter(([,v])=>v).map(([k,v])=><div key={t(k)}><dt>{t(k)}</dt><dd>{v}</dd></div>)}</dl></section>)}</div>;
}
export function QuoteForm(){const {t,language}=useLanguage();
 const [step,setStep]=useState(0),[sent,setSent]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[more,setMore]=useState(false);
 const heading=useRef<HTMLHeadingElement>(null),honeypot=useRef<HTMLInputElement>(null),submission=useRef({id:"",payload:""}),started=useRef(false),sending=useRef(false);
 const {register,control,watch,trigger,handleSubmit,getValues,reset,formState:{errors}}=useForm<QuoteInput,unknown,QuoteData>({resolver:zodResolver(quoteSchema),defaultValues:emptyQuote,mode:"onTouched"});
 const country=watch("country"),contact=watch("contact");
 useEffect(()=>{if(started.current)heading.current?.focus({preventScroll:true});else started.current=true;},[step,sent]);
 const field=(name:keyof QuoteInput,label:string,options:{placeholder?:string;type?:string;optional?:boolean;help?:string;autoComplete?:string;inputMode?:"numeric"|"decimal"|"tel"}={})=><div className="form-field" key={name}><label htmlFor={`q-${name}`}>{t(label)} {options.optional&&<span>{t("(optional)")}</span>}</label><Input id={`q-${name}`} {...register(name)} type={options.type||"text"} placeholder={options.placeholder?t(options.placeholder):undefined} autoComplete={options.autoComplete||"off"} inputMode={options.inputMode} aria-invalid={!!errors[name]} aria-describedby={errors[name]?`error-${name}`:options.help?`help-${name}`:undefined}/>{options.help&&<p id={`help-${name}`} className="field-hint">{t(options.help)}</p>}{errors[name]&&<p id={`error-${name}`} className="field-error" role="alert">{localizedError(language,errors[name]?.message)}</p>}</div>;
 const select=(name:keyof QuoteInput,label:string,items:readonly string[],help?:string)=><div className="form-field" key={name}><label htmlFor={`q-${name}`}>{t(label)}</label><Controller name={name} control={control} render={({field:f})=><Select value={String(f.value)} onValueChange={f.onChange}><SelectTrigger ref={f.ref} id={`q-${name}`} onBlur={f.onBlur} aria-invalid={!!errors[name]} aria-describedby={errors[name]?`error-${name}`:undefined}><SelectValue/></SelectTrigger><SelectContent position="popper">{items.map(i=><SelectItem key={i} value={i}>{t(i)}</SelectItem>)}</SelectContent></Select>}/>{help&&<p className="field-hint">{t(help)}</p>}{errors[name]&&<p id={`error-${name}`} className="field-error" role="alert">{localizedError(language,errors[name]?.message)}</p>}</div>;
 async function next(){setError("");if(await trigger(STEP_FIELDS[step],{shouldFocus:true}))setStep(v=>v+1);}
 async function send(data:QuoteData){data={...data,language};if(sending.current)return;sending.current=true;setBusy(true);setError("");try{
  const payload=JSON.stringify(data);if(submission.current.payload!==payload)submission.current={id:crypto.randomUUID(),payload};
  const r=await fetch("/api/quotes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({submissionId:submission.current.id,website:honeypot.current?.value||"",data})});const j=await r.json() as {error?:string;reference?:string;fields?:{field:string;message:string}[]};if(!r.ok)throw new Error(j.fields?.length?j.fields.map(f=>f.message).join("\n"):j.error||"Your request could not be sent. Please try again.");if(!j.reference)throw new Error("We couldn’t confirm your request. Please try again.");setSent(j.reference);
 }catch(e){setError(e instanceof Error?e.message:"Your request could not be sent. Please try again.");}finally{setBusy(false);sending.current=false;}}
 if(sent)return <div className="quote-success"><span className="success-icon"><CheckCircle2 size={42}/></span><p className="eyebrow">{t("YOUR NEXT CHAPTER STARTS HERE")}</p><h3 ref={heading} tabIndex={-1}>{t("We’ve received your request, {name}.",{name:getValues("name").split(" ")[0]})}</h3><p>{t("We’ll review your vehicle and contact you via {method} to discuss the next steps.",{method:t(getValues("contact"))})}</p><div className="reference"><span>{t("YOUR REQUEST REFERENCE")}</span><strong>{sent}</strong><small>{t("Keep this reference for any follow-up.")}</small></div><div className="success-next"><ClipboardCheck size={22}/><p>{t("If more vehicle information is needed, we’ll let you know. No payment or booking has been made.")}</p></div><button type="button" className="button button-outline" onClick={()=>{reset({...emptyQuote});setSent("");setStep(0);setMore(false);submission.current={id:"",payload:""};}}>{t("Request a quote for another vehicle")} <ArrowRight size={17}/></button></div>;
 return <div className="quote-form-wrap"><ol className="quote-steps" aria-label={t("Quote request progress")}>{steps.map((s,i)=><li key={t(s.title)} className={i===step?"current":i<step?"complete":""} aria-current={i===step?"step":undefined}><span>{i<step?<Check size={17}/>:i+1}</span><b>{t(s.title)}</b></li>)}</ol><Progress className="quote-progress" value={(step+1)*25} aria-label={t("Step {step} of 4",{step:step+1})}/>
 <form noValidate onSubmit={e=>{e.preventDefault();if(step<3)void next();else void handleSubmit(send,errs=>{const i=STEP_FIELDS.findIndex(keys=>keys.some(k=>errs[k]));if(i>=0)setStep(i);})()}}>
 <div className="form-heading"><span>{t("Step {step} of 4",{step:step+1})}</span><h3 ref={heading} tabIndex={-1}>{t(["First, let’s meet your vehicle.","Where is your journey taking you?","How can we reach you?","Everything looking right?"][step])}</h3><p>{t(["A few details help us understand exactly what you need.","Tell us a little about your plans for registration in Spain.","We’ll use these details to follow up on your quote request.","Check your details below. You can edit anything before sending."][step])}</p></div>
 {step===0&&<><div className="form-grid">{select("vehicleType","Vehicle type",TYPES)}{select("country","Currently registered in",COUNTRIES)}{country==="Other"&&field("otherCountry","Country of registration",{placeholder:"Enter country"})}{field("make","Make",{placeholder:"e.g. Volkswagen"})}{field("model","Model",{placeholder:"e.g. Golf"})}{field("year","First registration year",{placeholder:"e.g. 2019",inputMode:"numeric"})}{select("fuel","Fuel type",FUELS)}{field("variant","Version / engine description",{placeholder:"e.g. 2.0 TDI GTD",optional:true})}{field("registration","Current registration plate",{placeholder:"e.g. AB19 CDE",optional:true})}</div><button type="button" className="technical-toggle" aria-expanded={more} onClick={()=>setMore(!more)}><span><Car size={18}/> {t("Have the technical details handy?")}</span><span>{t(more?"Show less":"Add optional details")}<ChevronDown size={16} className={more?"rotated":""}/></span></button>{more&&<div className="form-grid technical-fields">{field("vin","VIN / chassis number",{optional:true,help:"Usually in section E of your registration document."})}{field("engineCC","Engine size (cc)",{optional:true,inputMode:"numeric",placeholder:"e.g. 1968"})}{field("co2","CO₂ emissions (g/km)",{optional:true,inputMode:"decimal",placeholder:"e.g. 124"})}{field("mileage","Mileage (km)",{optional:true,inputMode:"numeric",placeholder:"e.g. 75000"})}</div>}<p className="form-tip"><LockKeyhole size={15}/> {t("No documents to upload at this stage. Leave optional details blank if you’re unsure.")}</p></>}
 {step===1&&<div className="form-grid">{select("purpose","What brings you to us?",PURPOSES)}{select("inSpain","Is your vehicle already in Spain?",["Yes","No","Arriving soon"])}{select("province","Spanish province",PROVINCES)}{field("town","Town / municipality",{optional:true,placeholder:"e.g. Marbella"})}{select("steering","Steering position",["Left-hand drive","Right-hand drive","Not applicable / not sure"])}{select("timeframe","When are you looking to register?",["As soon as possible","Within 1 month","Within 3 months","Just planning"])}{select("coc","Do you have a Certificate of Conformity?",["Yes","No","Not sure"],"Often called a CoC. It confirms the vehicle’s technical specifications.")}{select("modified","Has the vehicle been modified?",["No","Yes","Not sure"],"For example, a camper conversion or changes to suspension or engine.")}</div>}
 {step===2&&<><div className="form-grid">{field("name","Full name",{placeholder:"Your full name",autoComplete:"name"})}{field("email","Email address",{type:"email",placeholder:"you@example.com",autoComplete:"email"})}{field("phone","Phone number",{type:"tel",inputMode:"tel",optional:contact==="Email",placeholder:"Include your country code",autoComplete:"tel"})}<div className="form-field"><label id="contact-label">{t("How would you prefer us to contact you?")}</label><Controller name="contact" control={control} render={({field:f})=><RadioGroup aria-labelledby="contact-label" className="contact-options" value={f.value} onValueChange={f.onChange}>{["Email","Phone","WhatsApp"].map(v=><label key={v}><RadioGroupItem value={v}/><span>{t(v)}</span></label>)}</RadioGroup>}/></div><div className="form-field full-field"><label htmlFor="q-notes">{t("Anything else we should know?")} <span>{t("(optional)")}</span></label><Textarea id="q-notes" {...register("notes")} maxLength={2000} placeholder={t("Tell us about modifications, your move, or any questions you have.")} rows={4}/>{errors.notes&&<p className="field-error">{localizedError(language,errors.notes.message)}</p>}<p className="field-hint">{t("Please don’t include passport numbers, payment details or other sensitive personal information.")}</p></div></div><div className="consent-field"><Controller name="consent" control={control} render={({field:f})=><Checkbox id="q-consent" ref={f.ref} checked={f.value} onCheckedChange={v=>f.onChange(v===true)} aria-invalid={!!errors.consent}/>}/><label htmlFor="q-consent">{t("I agree that CARREG SPAIN may use my vehicle and contact details to assess and respond to this request.")} <a href="/privacy" target="_blank" rel="noreferrer">{t("How we use your information")}</a>.</label></div>{errors.consent&&<p className="field-error" role="alert">{localizedError(language,errors.consent.message)}</p>}</>}
 {step===3&&<><QuoteSummary data={{...getValues(),language}} onEdit={setStep}/><p className="form-tip"><LockKeyhole size={16}/> {t("Sending this form requests a personalised assessment. It does not accept a price or book a service.")}</p></>}
 <div className="form-honeypot" aria-hidden="true"><label htmlFor="company-website">{t("Website")}</label><input id="company-website" ref={honeypot} tabIndex={-1} autoComplete="off"/></div>
 {error&&<div className="form-alert" role="alert">{localizedError(language,error)}</div>}
 <div className="form-actions">{step>0?<button type="button" className="back-button" disabled={busy} onClick={()=>{setError("");setStep(step-1)}}><ArrowLeft size={17}/> {t("Back")}</button>:<span className="required-note">{t("All fields required unless marked optional.")}</span>}<button type="submit" className="button button-red" disabled={busy}>{busy?<><Loader2 size={18} className="spin"/> {t("Sending your request…")}</>:step===3?<>{t("Send my quote request")} <ArrowRight size={18}/></>:<>{t("Continue")} <ArrowRight size={18}/></>}</button></div>
 </form></div>;
}
